### ISSUE TITLE
Add JSON API

### ISSUE THREAD

**Issue by jwilm** [collingreen/startuppong#14]
Please add a JSON API that accepts an access token retrieved from the account dashboard. In particular it would be nice to:

- fetch ladder including rank, name, ELO score
- create new matches (with optional scores)
- list recent matches

thanks!

**Comment by collingreen** [comment]
- [ ] Fetch Ladder (username, rank, rating, last game time, last game id?)
- [ ] Submit match (winnerid, loserid) -- current logic doesnt play nicely with allowing arbitrary game times
- [ ] Recent Matches for company
- [ ] Recent Matches including player
- [ ] Recent Matches including two players
